-- MySQL Script generated by MySQL Workbench
-- Sun Oct 31 23:34:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydbVideos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydbVideos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydbVideos` DEFAULT CHARACTER SET utf8 ;
USE `mydbVideos` ;

-- -----------------------------------------------------
-- Table `mydbVideos`.`usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbVideos`.`usuari` (
  `idusuari` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognom` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `data_registre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuari`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbVideos`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbVideos`.`video` (
  `idvideo` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(200) NOT NULL,
  `titol` VARCHAR(45) NOT NULL,
  `usuari_idusuari` INT NOT NULL,
  `data_pujada` DATETIME NOT NULL,
  `estat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvideo`),
  INDEX `fk_video_usuari1_idx` (`usuari_idusuari` ASC) VISIBLE,
  CONSTRAINT `fk_video_usuari1`
    FOREIGN KEY (`usuari_idusuari`)
    REFERENCES `mydbVideos`.`usuari` (`idusuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbVideos`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbVideos`.`tag` (
  `idtag` INT NOT NULL AUTO_INCREMENT,
  `nom_tag` VARCHAR(45) NOT NULL,
  `video_idvideo` INT NOT NULL,
  PRIMARY KEY (`idtag`),
  INDEX `fk_tag_video_idx` (`video_idvideo` ASC) VISIBLE,
  CONSTRAINT `fk_tag_video`
    FOREIGN KEY (`video_idvideo`)
    REFERENCES `mydbVideos`.`video` (`idvideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
